Library/Controllers/WritersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class WritersController : LibraryController
    {
        public ActionResult Index()
        {
            Models.LibraryTableAdapters.WritersTableAdapter writersAdapter = new Models.LibraryTableAdapters.WritersTableAdapter();
            Models.Library.WritersDataTable writersTable = new Models.Library.WritersDataTable();

            writersAdapter.Fill(writersTable);
            ViewData["writers"] = writersTable.Rows;
            ViewData["title"] = "Yazarlar";
            return View();
        }
        public ActionResult Add(string error = null)
        {
            ViewData["title"] = "Yazar ekle";
            if (error != null)
            {
                ViewData["error"] = error;
            }
            return View();
        }
        public void ProcessNewWriter(string writerName, string surname, string AKA)
        {
            Models.LibraryTableAdapters.WritersTableAdapter writersAdapter;

            if (writerName == null)
            {
                Response.Redirect("~/writers/add");
                return;
            }
            writerName = writerName.Trim();
            if (writerName == "")
            {
                Response.Redirect("~/writers/add");
                return;
            }
            if (writerName.Length > 100)
            {
                Response.Redirect("~/writers/add");
                return;
            }
            if (surname != null)
            {
                surname = surname.Trim();
                if (surname == "")
                {
                    surname = null;
                }
                else
                {
                    if (surname.Length > 50)
                    {
                        Response.Redirect("~/writers/add");
                        return;
                    }
                }
            }
            if (AKA != null)
            {
                AKA = AKA.Trim();
                if (AKA == "")
                {
                    AKA = null;
                }
                else
                {
                    if (AKA.Length > 50)
                    {
                        Response.Redirect("~/writers/add");
                        return;
                    }
                }
            }
            try
            {
                writersAdapter = new Models.LibraryTableAdapters.WritersTableAdapter();
                writersAdapter.AddWriter(writerName, surname, AKA);
                Response.Redirect("~/writers");
            }
            catch
            {
                Response.Redirect("~/writers/add");
            }
        }
        public void Delete(long id)
        {
            Models.LibraryTableAdapters.WritersTableAdapter writersAdapter = new Models.LibraryTableAdapters.WritersTableAdapter();

            writersAdapter.DeleteWriter(id);
            Response.Redirect("~/writers");
        }
        public ActionResult Update(long id, string error = null)
        {
            Models.LibraryTableAdapters.WritersTableAdapter writersAdapter = new Models.LibraryTableAdapters.WritersTableAdapter();
            Models.Library.WritersDataTable writersTable = new Models.Library.WritersDataTable();
            Models.Library.WritersRow writerRow;

            writersAdapter.FillById(writersTable, id);
            writerRow = (Models.Library.WritersRow)writersTable.Rows[0];
            ViewData["title"] = writerRow.WriterName;
            if (writerRow.IsWriterSurnameNull() == false)
            {
                ViewData["title"] = writerRow.WriterName + " " + writerRow.WriterSurname;
            }
            ViewData["writerRow"] = writerRow;
            if (error != null)
            {
                ViewData["error"] = error;
            }
            return View();
        }
        public void ProcessWriter(long id, string writerName, string surname, string AKA)
        {
            Models.LibraryTableAdapters.WritersTableAdapter writersAdapter;

            if (writerName == null)
            {
                Response.Redirect("~/writers/update/" + id.ToString());
                return;
            }
            writerName = writerName.Trim();
            if (writerName == "")
            {
                Response.Redirect("~/writers/update/" + id.ToString());
                return;
            }
            if (writerName.Length > 100)
            {
                Response.Redirect("~/writers/update/" + id.ToString());
                return;
            }
            if (surname != null)
            {
                surname = surname.Trim();
                if (surname == "")
                {
                    surname = null;
                }
                else
                {
                    if (surname.Length > 50)
                    {
                        Response.Redirect("~/writers/update/" + id.ToString());
                        return;
                    }
                }
            }
            if (AKA != null)
            {
                AKA = AKA.Trim();
                if (AKA == "")
                {
                    AKA = null;
                }
                else
                {
                    if (AKA.Length > 50)
                    {
                        Response.Redirect("~/writers/update/" + id.ToString());
                        return;
                    }
                }
            }
            try
            {
                writersAdapter = new Models.LibraryTableAdapters.WritersTableAdapter();
                writersAdapter.UpdateWriter(writerName, surname, AKA, id);
                Response.Redirect("~/writers");
            }
            catch
            {
                Response.Redirect("~/writers/update/" + id.ToString());
            }
        }
    }
}

Library/Views/Writers/Add.cshtml
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<form action="~/writers/processnewwriter" method="post">
    <input type="text" name="writerName" id="writerName" placeholder="Adı" data-val="true" data-val-required="Bu alan gerekli" maxlength="100" />
    <span class="field-validation-valid" data-valmsg-for="writerName" data-valmsg-replace="true"></span>
    <input type="text" name="surname" placeholder="Soyadı" maxlength="50" />
    <input type="text" name="AKA" placeholder="Mahlas" maxlength="50" />
    <input type="submit" value="TAMAM" />
</form>
@if (ViewData["error"] != null)
{
    <span>@ViewData["error"]</span>
}

Library/Views/Writers/Index.cshtml
@{
    System.Data.DataRowCollection writers = (System.Data.DataRowCollection)ViewData["writers"];
}
<script>
    function Delete(id) {
        if (confirm("Emin misiniz?") == true) {
            location.assign("@Url.Action("Delete","Writers")/" + id.toString());
        }
    }
</script>
<a href="~/writers/add">Ekle</a>
<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Adı</th>
            <th>Mahlas</th>
            <th></th>
        </tr>
    </thead>
    @foreach (Library.Models.Library.WritersRow writerRow in writers)
    {
        <tr>
            <td>
                <a href="~/writers/update/@writerRow.Id.ToString()">@writerRow.Id.ToString()</a>
            </td>
            <td>
                <span>@writerRow.WriterName</span>
                @if (writerRow.IsWriterSurnameNull() == false)
                {
                    <span>@writerRow.WriterSurname</span>
                }
            </td>
            <td>
                @if (writerRow.IsWriterAKANull() == false)
                {
                    <span>@writerRow.WriterAKA</span>
                }
            </td>
            <td>
                <button onclick="Delete(@writerRow.Id)">Sil</button>
            </td>
        </tr>
    }
</table>

Library/Views/Writers/Update.cshtml
@{
    Library.Models.Library.WritersRow writerRow = (Library.Models.Library.WritersRow)ViewData["writerRow"];
    string surname = "";
    string AKA = "";

    if (writerRow.IsWriterSurnameNull() == false)
    {
        surname = writerRow.WriterSurname;
    }
    if (writerRow.IsWriterAKANull() == false)
    {
        AKA = writerRow.WriterAKA;
    }
}
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<form action="~/writers/processwriter" method="post">
    <input type="text" name="writerName" id="writerName" placeholder="Adı" data-val="true" data-val-required="Bu alan gerekli" maxlength="100" value="@writerRow.WriterName" />
    <span class="field-validation-valid" data-valmsg-for="writerName" data-valmsg-replace="true"></span>
    <input type="text" name="surname" placeholder="Soyadı" maxlength="50" value="@surname" />
    <input type="text" name="AKA" placeholder="Mahlas" maxlength="50" value="@AKA" />
    <input type="hidden" name="id" value="@writerRow.Id" />
    <input type="submit" value="TAMAM" />
</form>
@if (ViewData["error"] != null)
{
    <span>@ViewData["error"]</span>
}