Library/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;

namespace Library.Controllers
{
    public class MembersController : LibraryController
    {
        public ActionResult Index()
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();
            Models.Library.MembersDataTable membersTable = new Models.Library.MembersDataTable();

            membersAdapter.Fill(membersTable);
            ViewData["members"] = membersTable.Rows;
            ViewData["title"] = "Üyeler";
            return View();
        }
        public void Delete(long id)
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();

            membersAdapter.DeleteMember(id);
            Response.Redirect("~/members");
        }
        public ActionResult Update(long id, string error = null)
        {
            Models.LibraryTableAdapters.MemberDetailsTableAdapter memberDetailsAdapter = new Models.LibraryTableAdapters.MemberDetailsTableAdapter();
            Models.Library.MemberDetailsDataTable memberDetailsTable = new Models.Library.MemberDetailsDataTable();
            Models.Library.MemberDetailsRow memberDetailsRow;

            memberDetailsAdapter.FillById(memberDetailsTable, id);
            memberDetailsRow = (Models.Library.MemberDetailsRow)memberDetailsTable.Rows[0];
            ViewData["title"] = memberDetailsRow.MemberName + " " + memberDetailsRow.MemberSurname;
            ViewData["memberRow"] = memberDetailsRow;
            if (error != null)
            {
                ViewData["error"] = error;
            }
            return View();
        }
        public void ProcessMember(long originalId, long memberId, string memberName, string surname, long phone, string eMail, string address, bool banned = false, bool? gender = null)
        {
            Models.LibraryTableAdapters.MembersTableAdapter membersAdapter;
            MailAddress mailAddress;

            if (memberId.ToString().Length != 11)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (memberName == null)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            memberName = memberName.Trim();
            if (memberName == "")
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (memberName.Length > 50)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (surname == null)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            surname = surname.Trim();
            if (surname == "")
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (surname.Length > 50)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (phone.ToString().Length != 10)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (eMail == null)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            eMail = eMail.Trim();
            if (eMail.Length > 100)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            try
            {
                mailAddress = new MailAddress(eMail);
            }
            catch
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (eMail != mailAddress.Address)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (address == null)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            address = address.Trim();
            if (address == "")
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            if (address.Length > 200)
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
                return;
            }
            try
            {
                membersAdapter = new Models.LibraryTableAdapters.MembersTableAdapter();
                membersAdapter.UpdateMember(memberId, memberName, surname, phone, eMail, gender, banned, address, originalId);
                Response.Redirect("~/members");
            }
            catch
            {
                Response.Redirect("~/members/update/" + originalId.ToString());
            }
        }
    }
}

Library/Views/Members/Index.cshtml
@{
    System.Data.DataRowCollection members = (System.Data.DataRowCollection)ViewData["members"];
    string banned;
}
<script>
    function Delete(id) {
        if (confirm("Emin misiniz?") == true) {
            location.assign("@Url.Action("Delete","Members")/" + id.toString());
        }
    }
</script>
<table>
    <thead>
        <tr>
            <th>T. C. Kimlik No</th>
            <th>Adı</th>
            <th>E-posta</th>
            <th>Cezalı</th>
            <th></th>
        </tr>
    </thead>
    @foreach (Library.Models.Library.MembersRow memberRow in members)
    {
        banned = "";
        if (memberRow.Banned == true)
        {
            banned = "checked";
        }
        <tr>
            <td>
                <a href="~/members/update/@memberRow.IdNo.ToString()">@memberRow.IdNo.ToString()</a>
            </td>
            <td>@memberRow.MemberName @memberRow.MemberSurname</td>
            <td>
                <a href="mailto:@memberRow.MemberEMail">@memberRow.MemberEMail</a>
            </td>
            <td>
                <input type="checkbox" readonly @banned />
            </td>
            <td>
                <button onclick="Delete(@memberRow.IdNo)">Sil</button>
            </td>
        </tr>
    }
</table>

Library/Views/Members/Update.cshtml
@{
    Library.Models.Library.MemberDetailsRow memberRow = (Library.Models.Library.MemberDetailsRow)ViewData["memberRow"];
    string male = "";
    string female = "";
    string banned = "";

    if (memberRow.IsGenderNull() == false)
    {
        if (memberRow.Gender == false)
        {
            female = "checked";
        }
        else
        {
            male = "checked";
        }
    }
    if (memberRow.Banned == true)
    {
        banned = "checked";
    }
}
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<form action="~/members/processmember" method="post">
    <input type="number" name="memberId" id="memberId" placeholder="T. C. Kimlik No" data-val="true" data-val-required="Bu alan gerekli" maxlength="11" value="@memberRow.IdNo.ToString()" />
    <span class="field-validation-valid" data-valmsg-for="memberId" data-valmsg-replace="true"></span>
    <input type="text" name="memberName" id="memberName" placeholder="Adı" data-val="true" data-val-required="Bu alan gerekli" maxlength="50" value="@memberRow.MemberName" />
    <span class="field-validation-valid" data-valmsg-for="memberName" data-valmsg-replace="true"></span>
    <input type="text" name="surname" id="surname" placeholder="Soyadı" data-val="true" data-val-required="Bu alan gerekli" maxlength="50" value="@memberRow.MemberSurname" />
    <span class="field-validation-valid" data-valmsg-for="surname" data-valmsg-replace="true"></span>
    <input type="number" name="phone" id="phone" placeholder="Telefon" data-val="true" data-val-required="Bu alan gerekli" maxlength="10" value="@memberRow.Phone.ToString()" />
    <span class="field-validation-valid" data-valmsg-for="phone" data-valmsg-replace="true"></span>
    <input type="email" name="eMail" id="eMail" placeholder="E-posta" data-val="true" data-val-required="Bu alan gerekli" data-val-email="Geçersiz e-posta" maxlength="100" value="@memberRow.MemberEMail" />
    <span class="field-validation-valid" data-valmsg-for="eMail" data-valmsg-replace="true"></span>
    <label for="maleRadio">Erkek</label>
    <input type="radio" name="gender" value="true" id="maleRadio" @male />
    <label for="femaleRadio">Kız</label>
    <input type="radio" name="gender" value="false" id="femaleRadio" @female />
    <label for="banned">Yasaklı</label>
    <input type="checkbox" name="banned" value="true" @banned />
    <textarea name="address" id="address" data-val="true" data-val-required="Bu alan gerekli" maxlength="200">@memberRow.MemberAddress</textarea>
    <span class="field-validation-valid" data-valmsg-for="address" data-valmsg-replace="true"></span>
    <input type="hidden" name="originalId" value="@memberRow.IdNo.ToString()" />
    <input type="submit" value="TAMAM" />
</form>
@if (ViewData["error"] != null)
{
    <span>@ViewData["error"]</span>
}